### PR TITLE
Create 350_intersection_arrays

### PR DESCRIPTION
**Pull request by jsingh41**
@sb2nov

### CODE REVIEW

**Review by sb2nov — APPROVED** [review]
One other way to do this might be to create two maps with counters for each number and then just iterating on the smaller one after that. 

That would have lesser time complexity than this as it is N^2 right now. But this works so not an issue.

**Comment by jsingh41** [comment]
How is this n^2? is the count(i) function n^2?

**Comment by sb2nov** [comment]
No count is O(N) but you're doing it in a loop so those added is N^2

**Comment by jsingh41** [comment]
Merging for now, but will re-do this later

**Pull request merged**
